name: lib_image_loader
description: Flutter image loading wrapper with a swappable kernel, aligned with Android lib_imageloader.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
