// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../demos/storage/objectbox/objectbox_task_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6875918576692746143),
    name: 'ObjectBoxTaskEntity',
    lastPropertyId: const obx_int.IdUid(7, 8634949554448391379),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7597784480635288144),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3636481696241980174),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5854153189975116788),
        name: 'detail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5354749237927639778),
        name: 'priority',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5277984201006320613),
        name: 'isDone',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6753696880245341878),
        name: 'isStarred',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8634949554448391379),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6875918576692746143),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ObjectBoxTaskEntity: obx_int.EntityDefinition<ObjectBoxTaskEntity>(
      model: _entities[0],
      toOneRelations: (ObjectBoxTaskEntity object) => [],
      toManyRelations: (ObjectBoxTaskEntity object) => {},
      getId: (ObjectBoxTaskEntity object) => object.id,
      setId: (ObjectBoxTaskEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxTaskEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final detailOffset = fbb.writeString(object.detail);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, detailOffset);
        fbb.addInt64(3, object.priority);
        fbb.addBool(4, object.isDone);
        fbb.addBool(5, object.isStarred);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final detailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final priorityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final isDoneParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final isStarredParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = ObjectBoxTaskEntity(
          id: idParam,
          title: titleParam,
          detail: detailParam,
          priority: priorityParam,
          isDone: isDoneParam,
          isStarred: isStarredParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ObjectBoxTaskEntity] entity fields to define ObjectBox queries.
class ObjectBoxTaskEntity_ {
  /// See [ObjectBoxTaskEntity.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxTaskEntity>(
    _entities[0].properties[0],
  );

  /// See [ObjectBoxTaskEntity.title].
  static final title = obx.QueryStringProperty<ObjectBoxTaskEntity>(
    _entities[0].properties[1],
  );

  /// See [ObjectBoxTaskEntity.detail].
  static final detail = obx.QueryStringProperty<ObjectBoxTaskEntity>(
    _entities[0].properties[2],
  );

  /// See [ObjectBoxTaskEntity.priority].
  static final priority = obx.QueryIntegerProperty<ObjectBoxTaskEntity>(
    _entities[0].properties[3],
  );

  /// See [ObjectBoxTaskEntity.isDone].
  static final isDone = obx.QueryBooleanProperty<ObjectBoxTaskEntity>(
    _entities[0].properties[4],
  );

  /// See [ObjectBoxTaskEntity.isStarred].
  static final isStarred = obx.QueryBooleanProperty<ObjectBoxTaskEntity>(
    _entities[0].properties[5],
  );

  /// See [ObjectBoxTaskEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ObjectBoxTaskEntity>(
    _entities[0].properties[6],
  );
}
