name: lib_storage
description: Flutter key-value storage wrapper with a swappable kernel (Hive by default).
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/hive
  hive: ^2.2.3
  # https://pub.dev/packages/hive_flutter
  hive_flutter: ^1.1.0
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  # 测试用内存实现
  # https://pub.dev/packages/shared_preferences_platform_interface
  shared_preferences_platform_interface: ^2.4.1
